[project]
channels = ["conda-forge"]
description = "Beamline profile for xf31id1"
name = "TST-profile-collection"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]

libc = "2.17"


[feature.profile.dependencies]
ophyd = "*"
pyepics = "*"
ipython = "*"
tiled-client = ">=0.1.0b11,<0.2"
matplotlib = ">=3.9.3,<4"
numpy = "*"
bluesky = "*"
python = "*"
epicscorelibs = "*"
nslsii = ">=0.11.1,<0.12"
networkx = ">=3.4.2,<4"
ply = ">=3.11,<4"
pydantic-numpy = "*"
semver = ">=3.0.4,<4"
colorlog = ">=6.9.0,<7"
nose2 = ">=0.9.2,<0.10"
epics-base = ">=7.0.7.0,<8"

[feature.profile.pypi-dependencies]
ophyd-async = { version = ">=0.9.0, <0.10", extras = ["ca", "pva"] }

[feature.qs.dependencies]
bluesky-queueserver = "*"


[feature.qs.tasks]
qs = "start-re-manager --profile-dir=."


[feature.terminal.dependencies]
ipython = "*"
pyside6 = "*"


[feature.terminal.tasks]
bsui = "ipython --profile-dir=."


[environments]
bsui = {features=["profile", "terminal"], solve-group="profile"}
qs = {features=["profile", "qs"], solve-group="profile"}
