[project]
channels = ["conda-forge"]
description = "Beamline profile for xf31id1"
name = "TST-profile-collection"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[system-requirements]

libc = "2.17"

[feature.dev.dependencies]
black = "*"
pre-commit = ">=4.2.0,<5"

[feature.profile]
platforms = ["linux-64"]

[feature.profile.dependencies]
bluesky-base = "*"
bluesky-queueserver = "*"
matplotlib-base = ">=3.9.3,<4"
numpy = "*"
ophyd = "*"
pyepics = "*"
python = ">3.12"
tiled-client = ">=0.1.0b11,<0.2"
nslsii = "*"

# needed until we get p4p packaged
nose2 = ">=0.9.2,<0.10"
ply = ">=3.11,<4"
# needed until we get ophyd-async packaged
colorlog = ">=6.9.0,<7"
epicscorelibs = "*"
pydantic-numpy = "*"


[feature.qs]
platforms = ["linux-64"]

[feature.qs.dependencies ]
"bluesky-httpserver" = "*"


[feature.profile.pypi-dependencies]
ophyd-async = { version = ">=0.9.0, <0.10", extras = ["ca", "pva"] }



[feature.qs.tasks]
qs = "start-re-manager --profile-dir=."


[feature.terminal.dependencies]
ipython = "*"
pyside6 = "*"


[feature.terminal.tasks]
bsui = "ipython --profile-dir=."
pvs = "ipython --profile-dir=. -c 'get_pv_types(); exit()'"

[feature.dev.tasks]
black = "black ."
pre-commit = "pre-commit run --all-files"

[environments]
bsui = {features=["profile", "terminal"], solve-group="profile"}
qs = {features=["profile", "qs"], solve-group="profile"}
dev = {features=["dev"], no-default-feature = true}
