print_summary(
    xas_demo_async(panda1, None, npoints=10_000, total_time=1, start_e=10, end_e=190)
)
(uid,) = RE(
    xas_demo_async(panda1, None, npoints=10_000, total_time=1, start_e=10, end_e=190)
)
print(uid)
print(tiled_client[uid]["panda1_async_stream"])
print(tiled_client[uid]["panda1_async_stream"]["external"])
print(tiled_client[uid]["panda1_async_stream"]["external"]["I0"])
print(tiled_client[uid]["panda1_async_stream"]["external"]["I0"].read())
print(tiled_client[uid]["panda1_async_stream"]["external"]["I0"].read().shape)
print(tiled_client[uid]["panda1_async_stream"]["external"]["I1"].read())
print(tiled_client[uid]["panda1_async_stream"]["external"]["I1"].read().shape)
print(tiled_client[uid]["panda1_async_stream"]["external"]["Pos"].read())
print(tiled_client[uid]["panda1_async_stream"]["external"]["Pos"].read().shape)
